### PR TITLE
UI-Improvements 

### LINKED ISSUE #83: Switch from session- to localStorage for better user experience
At the moment opening a new tab to the same site will not be logged in.

### PR DESCRIPTION
**Pull request by jmetz**
See #65  for details. First commit addresses #83 

* fix: switch to localStorage for better user experience, closes #83

### CODE REVIEW

**Comment by jmetz** [comment]
@FynnBe + @oeway : for reviewing, please use the sandbox for any staging + publishing workflows. The non-sandbox can be used for staging in principle... but definitely not for publishing as a test.

The sandbox for this PR is: https://deploy-preview-84--bioimageio-uploader.netlify.app/sandbox/

**Comment by FynnBe** [comment]
> EDIT: Also @oeway will likely have to upgrade and restart the upload service for this to work.

I suppose that service restart has not happened yet.. 
[status page ](https://deploy-preview-84--bioimageio-uploader.netlify.app/sandbox/#/status) looks like this rn:

image

**Comment by oeway** [comment]
Hi, Just pulled and restarted, let me know if you need me to do it again.

**Comment by FynnBe** [comment]
somewhat works now, but we should add the `status` for each entry

**Comment by oeway** [comment]
I will merge it and see.

**Pull request merged**
