### PR TITLE
Add validation in CI

### PR DESCRIPTION
**Pull request by FynnBe**

### CODE REVIEW

**Comment by jmetz** [comment]
@FynnBe  is 2-spaces the norm for yaml? Find 2-spaces not great for an indentation-based syntax...

**Comment by FynnBe** [comment]
> @FynnBe is 2-spaces the norm for yaml? Find 2-spaces not great for an indentation-based syntax...

sometimes deep nesting in gh workflows can get a bit wide with 4 spaces, but I don't have a strong opinion. changed back to 4 spaces now.

**Review by jmetz — APPROVED** [review]
Looks good to me!

**Comment by jmetz** [comment]
Are you still adding stuff @FynnBe or can you mark this as ready to merge?

**Comment by FynnBe** [comment]
> Are you still adding stuff @FynnBe or can you mark this as ready to merge?

well, it's missing pieces from your latest changes.. 
`add_log_entry` does not exist for example

**Pull request merged**
